default:
  image: node:16-alpine

pages:
  stage: deploy
  script:
    - cd site
    - npm install
    - npm run build -- --base=/to-tree-string
    - mv ./dist ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
