default:
  image: node:16-alpine

pages:
  stage: deploy
  script:
    - npm --prefix site install
    - npm --prefix site run build
    - mv ./site/dist ./public
  artifacts:
    paths:
      - dist
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
